version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root